/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct magic_set {
    _unused: [u8; 0],
}
pub type magic_t = *mut magic_set;
extern "C" {
    pub fn magic_open(arg1: ::std::os::raw::c_int) -> magic_t;
}
extern "C" {
    pub fn magic_close(arg1: magic_t);
}
extern "C" {
    pub fn magic_getpath(
        arg1: *const ::std::os::raw::c_char,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn magic_file(
        arg1: magic_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn magic_descriptor(
        arg1: magic_t,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn magic_buffer(
        arg1: magic_t,
        arg2: *const ::std::os::raw::c_void,
        arg3: usize,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn magic_error(arg1: magic_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn magic_getflags(arg1: magic_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_setflags(arg1: magic_t, arg2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_version() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_load(arg1: magic_t, arg2: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_load_buffers(
        arg1: magic_t,
        arg2: *mut *mut ::std::os::raw::c_void,
        arg3: *mut usize,
        arg4: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_compile(
        arg1: magic_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_check(arg1: magic_t, arg2: *const ::std::os::raw::c_char)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_list(arg1: magic_t, arg2: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_errno(arg1: magic_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_setparam(
        arg1: magic_t,
        arg2: ::std::os::raw::c_int,
        arg3: *const ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn magic_getparam(
        arg1: magic_t,
        arg2: ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
